name: Blazemeter


on: 
  workflow_dispatch:
  schedule:
      - cron: '0 */3 * * *'


jobs:
  build:
    runs-on: ubuntu-latest
   
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 
      uses: actions/setup-java@v4
      with:
        java-version: 17
        cache: maven
        distribution: 'adopt'
        token: ${{ secrets.testsuite_pat }}
        
    - name: Adding secret
      
    - name: Test with Maven
      env:
        run: mvn -f ./pom.xml clean install -DsuiteXmlFile=FUI-PostDeploymentSanity.xml -Dremoteurl=$remoteurl

   
